import { IEntitySchema } from "@drax/arch";

const schema: IEntitySchema = {
    module: "redmine",
    name: "RedmineIssueAnalysis",
    apiBasePath: "redmine-issue-analyses",
    collectionName: "redmineissueanalyses",
    apiTag: "redmine",
    tabs: ["General", "Clasificacion", "Seniales"],
    schema: {
        redmineIssue: {
            type: "ref",
            required: true,
            ref: "RedmineIssue",
            refDisplay: "subject",
            index: true,
            unique: true,
            header: true,
            groupTab: "General",
        },
        resumen: {
            type: "longString",
            required: false,
            search: true,
            header: false,
            groupTab: "General",
        },
        categoria: {
            type: "enum",
            required: false,
            enum: [
                "nueva_funcionalidad",
                "error",
                "soporte",
                "mantenimiento",
                "refactorizacion",
                "investigacion",
                "configuracion",
                "documentacion",
                "tarea_tecnica",
                "integracion",
                "optimizacion",
                "seguridad",
                "datos",
                "infraestructura",
                "otro",
            ],
            header: true,
            groupTab: "Clasificacion",
        },
        tipoObjetivo: {
            type: "enum",
            required: false,
            enum: [
                "nueva_capacidad",
                "correccion_de_falla",
                "estabilidad",
                "reduccion_de_deuda_tecnica",
                "soporte_operativo",
                "cumplimiento",
                "mejora_experiencia_usuario",
                "reduccion_de_costos",
                "investigacion",
                "automatizacion",
                "escalabilidad",
                "observabilidad",
                "otro",
            ],
            header: true,
            groupTab: "Clasificacion",
        },
        nivelValor: {
            type: "enum",
            required: false,
            enum: ["muy_bajo", "bajo", "medio", "alto", "muy_alto"],
            header: true,
            groupTab: "Clasificacion",
        },
        nivelComplejidad: {
            type: "enum",
            required: false,
            enum: ["muy_baja", "baja", "media", "alta", "muy_alta"],
            header: true,
            groupTab: "Clasificacion",
        },
        nivelUrgencia: {
            type: "enum",
            required: false,
            enum: ["muy_baja", "baja", "media", "alta", "muy_alta"],
            header: true,
            groupTab: "Clasificacion",
        },
        esError: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Clasificacion",
        },
        esRetrabajo: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Clasificacion",
        },
        esCambioMenor: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Clasificacion",
        },
        estaBloqueado: {
            type: "boolean",
            required: false,
            default: false,
            header: true,
            groupTab: "Clasificacion",
        },
        motivoRetrabajo: {
            type: "enum",
            required: false,
            enum: [
                "correccion_de_error_en_produccion",
                "correccion_de_error_previo_a_produccion",
                "cambio_de_requerimiento",
                "caso_no_contemplado",
                "ajuste_funcional",
                "ajuste_tecnico",
                "refactorizacion_necesaria",
                "problema_de_calidad",
                "problema_de_testing",
                "problema_de_comunicacion",
                "dependencia_externa",
                "desconocido",
            ],
            header: false,
            groupTab: "Clasificacion",
        },
        areasImpacto: {
            type: "array.enum",
            required: false,
            enum: [
                "backend",
                "frontend",
                "base_de_datos",
                "infraestructura",
                "devops",
                "integraciones",
                "seguridad",
                "experiencia_usuario",
                "datos",
                "reporting",
                "api",
                "arquitectura",
                "testing",
            ],
            header: false,
            groupTab: "Clasificacion",
        },
        grupoObjetivo: {
            type: "string",
            required: false,
            search: true,
            header: false,
            groupTab: "Clasificacion",
        },
        areaFuncional: {
            type: "string",
            required: false,
            search: true,
            header: false,
            groupTab: "Clasificacion",
        },
        resultadoProbable: {
            type: "enum",
            required: false,
            enum: [
                "valor_directo_para_negocio",
                "mejora_de_calidad",
                "continuidad_operativa",
                "reduccion_de_riesgo",
                "mejora_tecnica_interna",
                "habilitador_para_trabajo_futuro",
                "bajo_valor_visible",
                "sin_valor_claro",
            ],
            header: true,
            groupTab: "Clasificacion",
        },
        senialesDesperdicio: {
            type: "array.enum",
            required: false,
            enum: [
                "requerimiento_poco_claro",
                "cambio_muy_pequenio",
                "exceso_de_coordinacion",
                "retrabajo",
                "operacion_manual",
                "bajo_impacto_de_negocio",
                "duplicacion_de_esfuerzo",
                "dependencia_evita_avance",
                "analisis_excesivo",
                "espera_prolongada",
            ],
            header: false,
            groupTab: "Seniales",
        },
        senialesProceso: {
            type: "array.enum",
            required: false,
            enum: [
                "buena_definicion",
                "mala_definicion",
                "cambio_de_alcance",
                "demora_por_dependencia",
                "gap_de_testing",
                "resolucion_rapida",
                "estimacion_desviada",
                "prioridad_inestable",
                "falta_de_contexto",
                "buena_colaboracion",
                "alto_ida_y_vuelta",
            ],
            header: false,
            groupTab: "Seniales",
        },
        confianza: {
            type: "number",
            required: false,
            header: true,
            groupTab: "General",
        },
    },
};

export default schema;
export { schema };
